//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by VirtualCar.rc
//
#define IDD_VIRTUALCAR_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDI_DIAGNOTOR                   130
#define IDI_CAR                         131
#define IDI_NOTE                        132
#define IDI_ERR                         133
#define IDR_MENU_POPUP                  134
#define IDD_DIALOG_ABOUT                137
#define IDR_MENU                        138
#define IDD_DIALOG_MODIFY               144
#define IDR_MENU_MODIFY_POPUP           145
#define IDD_DIALOG_EXP_SWITCH           147
#define IDD_DIALOG_INPUT_BYTE           148
#define IDD_DIALOG_PARAS                149
#define IDD_DIALOG_WIZARD_NEWFILE       150
#define IDB_BITMAP_WIZARD               152
#define IDD_DIALOG_WIZARD_TITLE         153
#define IDD_DIALOG_WIZARD_PERFORMANCE   154
#define IDD_DIALOG_WIZARD_COM           155
#define IDD_DIALOG_WIZARD_FRAME         157
#define IDD_DIALOG_WIZARD_CHECK         158
#define IDD_DIALOG_WIZARD_TIMER         159
#define IDD_DIALOG_WIZARD_COMM          160
#define IDD_DIALOG_SEND                 162
#define IDC_LIST                        1000
#define IDC_INPUT_TEMP                  1006
#define IDC_CHECK_WATCH_LIST            1017
#define IDC_CHECK_LOG_FILE              1018
#define IDC_EDIT_SLEEP                  1019
#define IDC_CHECK_REMOVE_SELF_SEND      1020
#define IDC_CHECK_SHOW_COMM_ERR         1021
#define IDC_CHECK_REPLACE_SEND_DATA     1022
#define IDC_CHECK_AUTO_REPLY_BY_TEMP    1023
#define IDC_BUTTON_SEND                 1024
#define IDC_EDIT_AUTO_REPLY_ID          1025
#define IDC_EDIT_AUTO_REPLY_SPACE       1026
#define IDC_SLIDER_SLEEP                1027
#define IDC_SLIDER_PRIORITY             1028
#define IDC_RADIO_TIMER_FILE            1029
#define IDC_EDIT_REPLACE_CHECK_SYMBOL   1030
#define IDC_RADIO_TIMER_TEMP            1031
#define IDC_BUTTON_CLEAN_LIST           1032
#define IDC_EDIT_PRIORITY               1033
#define IDC_EDIT_REPLACE_POS1           1034
#define IDC_BUTTON_CLEAN_LOG            1035
#define IDC_CHECK_TIMER_REPLY           1036
#define IDC_BUTTON_RELOAD               1037
#define IDC_EDIT_REPLACE_TO1            1038
#define IDC_PROGRESS_INPUT              1039
#define IDC_PROGRESS_OUTPUT             1040
#define IDC_EDIT_PORT_STATE             1041
#define IDC_EDIT_REPLACE_POS2           1042
#define IDC_EDIT_REPLACE_TO2            1043
#define IDC_CHECK_REPLACE_CHECK         1044
#define IDC_EDIT_REPLACE_SYMBOL         1045
#define IDC_SPIN_POS1                   1046
#define IDC_SPIN_TO1                    1047
#define IDC_SPIN_POS2                   1048
#define IDC_SPIN_TO2                    1049
#define IDC_BUTTON_TAO                  1050
#define IDC_EDIT_CHECKOUT_BEGIN         1051
#define IDC_CHECK_REPLACE_SEND_DATA2    1052
#define IDC_EDIT_CHECKOUT_TARGET        1053
#define IDC_EDIT_CHECKOUT_END           1054
#define IDC_COMBO_REPLACE_CHECK_TYPE    1055
#define IDC_EDIT_REPLACE_SYMBOL2        1056
#define IDC_CHECK_PAUSE                 1057
#define IDC_COMBO_FRAME_TYPE            1058
#define IDC_BUTTON_CLEAR_SEND           1059
#define IDC_BUTTON_SEND_COMM            1060
#define IDC_BUTTON_00                   1061
#define IDC_BUTTON_NEXT                 1061
#define IDC_CHECK_DISABLE_REPAY         1061
#define IDC_BUTTON_01                   1062
#define IDC_BUTTON_IGNORE               1062
#define IDC_EDIT_DISABLE_REPAY_SYMBOL   1062
#define IDC_BUTTON_7F                   1063
#define IDC_BUTTON_RESET                1064
#define IDC_BUTTON_80                   1065
#define IDC_BUTTON_FF                   1066
#define IDC_BUTTON_FREE                 1067
#define IDC_BUTTON_SAVE_ROW             1068
#define IDC_BUTTON_SAVEALL              1069
#define IDC_BUTTON_DOUBLE_RANDOM        1070
#define IDC_BUTTON_MODIFY_ADD1          1071
#define IDC_BUTTON_MODIFY_SUB01         1072
#define IDC_CHECK_ALLWAYS               1073
#define IDC_BUTTON_STAR                 1074
#define IDC_BUTTON_MODIFY_ADD10         1075
#define IDC_EDIT1                       1075
#define IDC_EDIT_DATA                   1075
#define IDC_BUTTON_MODIFY_SUB10         1076
#define IDC_EDIT                        1076
#define IDC_EDIT_RECEIVEDELAY           1076
#define IDC_BUTTON_MODIFY_MOVELEFT      1077
#define IDC_STATIC_TEMP_FRAME           1077
#define IDC_EDIT_SENDDELAY              1077
#define IDC_BUTTON_MODIFY_MOVELEFT2     1078
#define IDC_BUTTON_MODIFY_MOVERIGHT     1078
#define IDC_STATIC_COM1                 1078
#define IDC_EDIT_SYMBOL                 1078
#define IDC_BUTTON_MODIFY_ADD_ANY       1079
#define IDC_STATIC_INPUT                1079
#define IDC_BUTTON_MODIFY_SUB_ANY       1080
#define IDC_STATIC_OUTPUT               1080
#define IDC_STATIC_PREFORMANCE_FRAME    1081
#define IDC_STATIC_CPU1                 1082
#define IDC_STATIC_CPU2                 1083
#define IDC_STATIC_TIMER_FRAME          1084
#define IDC_STATIC_TIMER_ID             1085
#define IDC_STATIC_TIMER_INTERVAL       1086
#define IDC_STATIC_CHECK_FRAME          1087
#define IDC_STATIC_CHECK_SYMBOL         1088
#define IDC_STATIC_COM4                 1089
#define IDC_STATIC_CHECK_BEGINPOS       1090
#define IDC_STATIC_CHECK_ENDPOS         1091
#define IDC_STATIC_CHECK_TARGETPOS      1092
#define IDC_STATIC_CHECKTYPE            1093
#define IDC_STATIC_REPLACE_FRAME        1094
#define IDC_STATIC_REPLACE_SYMBOL       1095
#define IDC_STATIC_RPOS1                1096
#define IDC_STATIC_RAS1                 1097
#define IDC_STATIC_RPOS2                1098
#define IDC_STATIC_RAS2                 1099
#define IDC_STATIC_REPLACE_FRAME2       1100
#define IDC_LIST_PARAS                  1100
#define IDC_STATIC_REPLACE_SYMBOL2      1101
#define IDC_BUTTON_BROWSE               1101
#define IDC_STATIC_MORE_FRAME           1102
#define IDC_EDIT_FILE                   1102
#define IDC_CHECK_LOGENABLE             1103
#define IDC_EDIT_LOGFILE                1104
#define IDC_STATIC_DISABLE_REPAY_SYMBOL 1104
#define IDC_EDIT_TITLE                  1105
#define IDC_CHECK_FILTER_SELF_SENT      1106
#define IDC_COMBO_SPEED                 1109
#define IDC_COMBO_PORT                  1110
#define IDC_COMBO_BITS                  1111
#define IDC_COMBO_FRAMETYPE             1111
#define IDC_COMBO_STOPBITS              1112
#define IDC_CHECK_DELAYREALTIME         1112
#define IDC_COMBO_PARITY                1113
#define IDC_EDIT_MINIFRAMESPACE         1113
#define IDC_CHECK_REPLACECHECK          1114
#define IDC_COMBO_CHECKTYPE             1115
#define IDC_EDIT_BEGIN                  1116
#define IDC_EDIT_END                    1117
#define IDC_EDIT_TARGET                 1118
#define IDC_CHECK_REPLYBYMANUAL         1119
#define IDC_EDIT_MANUALDATA             1120
#define IDC_COMBO_AUTOREPLYENABLE       1121
#define IDC_EDIT_ID                     1122
#define IDC_EDIT_SPACE                  1123
#define IDC_EDIT_GRIDX_OFFSET           1124
#define IDC_CHECK_HEX0DEC1              1126
#define IDC_LIST_SEND                   1129
#define IDC_COMBO1                      1131
#define ID_MENUITEM_CLOSE               32771
#define ID_MENUITEM_CLEAR_LIST          32774
#define ID_MENUITEM_VIEW_LOG            32776
#define ID_MENUITEM_ABOUT               32777
#define ID_MENUITEM_HELP                32778
#define ID_MENUITEM_LOAD_CONFIG         32779
#define ID_MENUITEM_EDIT_CONFIG         32780
#define ID_MENUITEM_RELOAD_CONFIG       32782
#define ID_MENUITEM_CLEAN_LOG           32783
#define ID_MENUITEM_LOG_TIME            32784
#define ID_MENUITEM_LOGOPEN             32785
#define ID_MENUITEM_WATCH_LIST          32786
#define ID_MENUITEM_MODIFY_REPLACE_00   32792
#define ID_MENUITEM_MODIFY_REPLACE_7F   32793
#define ID_MENUITEM_MODIFY_REPLACE_80   32794
#define ID_MENUITEM_MODIFY_REPLACE_01   32795
#define ID_MENUITEM_MODIFY_REPLACE_FF   32796
#define ID_MENUITEM_FREE                32797
#define ID_MENUITEM_SAVE_ROW            32798
#define ID_MENUITEM_MODIFY_REPLACE_DRAN 32803
#define ID_MENUITEM_ADD01               32804
#define ID_MENUITEM_SUB01               32805
#define ID_MENUITEM_ADD10               32806
#define ID_MENUITEM_SUB10               32807
#define ID_MENUITEM_MOVELEFT            32808
#define ID_MENUITEM_MOVERIGHT           32809
#define ID_MENUITEM_ALWAYS_ADD01        32810
#define ID_MENUITEM_ALWAYS_SUB01        32811
#define ID_MENUITEM_ALWAYS_ADD10        32812
#define ID_MENUITEM_ALWAYS_SUB10        32813
#define ID_MENUITEM_ALWAYS_MOVELEFT     32814
#define ID_MENUITEM_ALWAYS_MOVERIGHT    32815
#define ID_MENUITEM_MODIFY_REPLACE_STAR 32817
#define ID_MENUITEM_AUTOLOAD            32818
#define ID_MENUITEM_TOOL_TAO            32819
#define ID_MENUITEM_TOOL_ULTRAEDITOR    32820
#define ID_MENUITEM_TOOL_DATACONVERTOR  32821
#define ID_MENUITEM_ALWAYS_ADDANY       32823
#define ID_MENUITEM_ALWAYS_SUBANY       32824
#define ID_MENUITEM_NEW_CONFIG          32825
#define ID_MENUITEM_PARAS               32826
#define ID_MENUITEM_FILTER_SELF_SENT    32827
#define ID_MENUITEM_IMPORT_COMM         32828
#define ID_MENUITEM_MODIFY_APP_CONFIG   32829
#define ID_MENUITEM_INSERT_CFG          32830
#define ID_MENUITEM_CONVERT_VIRTUALCAR1 32831
#define ID_MENUITEM_ADDA5A5             32832
#define ID_MENUITEM_REMOVEA5A5          32833
#define ID_MENUITEM_PAUSE               32834
#define ID_MENUITEM_CLEAR_INBUFFER      32835
#define ID_MENUITEM_CLEAR_OUTBUFFER     32836
#define ID_MENUITEM_COPYALL             32837
#define ID_MENUITEM_CONVERT_KIA         32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32839
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
